env:
  node: true
  es6: true
  jest: true
parser: 'babel-eslint'
plugins:
  - flowtype
extends:
  - 'eslint:recommended'
  - 'plugin:flowtype/recommended'
rules:
  semi:
    - error
    - never
  no-console: off
  comma-dangle:
    - error
    - arrays: always-multiline
      objects: always-multiline
      imports: always-multiline
      exports: always-multiline
      functions: always-multiline
  no-cond-assign: off
