env:
  node: true
  es6: true
  jest: true
parser: babel-eslint
plugins:
  - flowtype
extends:
  - eslint:recommended
  - plugin:flowtype/recommended
rules:
  semi:
    - error
    - never
  flowtype/semi:
    - error
    - never
  no-console: off
  comma-dangle:
    - error
    - always-multiline
  no-cond-assign: off
